import { notFound } from 'next/navigation';
import { getAdminProjectDetails } from '@/app/actions/admin';
import { DataTable } from '@/components/admin/data-table';
import { StatusBadge } from '@/components/admin/status-badge';
import { DeleteProjectButton } from '../delete-project-button';

type Props={params:Promise<{id:string}>}; export const dynamic='force-dynamic';
export default async function AdminProjectDetailsPage({params}:Props){const {id}=await params;const data=await getAdminProjectDetails(Number(id));if(!data)notFound();const p=data.project;return <div className="space-y-6"><div className="rounded-2xl bg-[#1a1a2e] p-6 text-white"><h1 className="text-3xl font-extrabold">{p.title}</h1><p className="mt-2 text-slate-300">{p.clientName??'—'}</p><div className="mt-4 flex flex-wrap gap-2"><StatusBadge status={p.status}>{p.status}</StatusBadge><DeleteProjectButton projectId={p.id} mode="disable"/><DeleteProjectButton projectId={p.id}/></div></div><section className="rounded-2xl border bg-white p-6"><h2 className="text-xl font-extrabold text-[#1a1a2e]">تفاصيل المشروع</h2><p className="mt-3 leading-7 text-slate-700">{p.description}</p><div className="mt-4 grid gap-3 md:grid-cols-3"><Info label="الميزانية" value={`${p.budgetMin} - ${p.budgetMax}`}/><Info label="المدة" value={`${p.durationDays} يوم`}/><Info label="التاريخ" value={p.createdAt.toLocaleDateString('ar')}/></div></section><section className="space-y-3"><h2 className="text-xl font-extrabold text-[#1a1a2e]">العروض</h2><DataTable columns={['المستقل','المبلغ','المدة','الحالة','التاريخ']} empty={data.proposals.length===0}>{data.proposals.map((r)=><tr key={r.id}><td className="px-4 py-3">{r.freelancerName}</td><td className="px-4 py-3">{r.amount}</td><td className="px-4 py-3">{r.durationDays} يوم</td><td className="px-4 py-3"><StatusBadge status={r.status}>{r.status}</StatusBadge></td><td className="px-4 py-3">{r.createdAt.toLocaleDateString('ar')}</td></tr>)}</DataTable></section></div>}
function Info({label,value}:{label:string;value:React.ReactNode}){return <div className="rounded-xl bg-slate-50 p-4"><p className="text-xs font-bold text-slate-500">{label}</p><p className="mt-1 font-extrabold text-[#1a1a2e]">{value}</p></div>}
