import { getAdminReports } from '@/app/actions/admin';
import { StatCard } from '@/components/admin/stat-card';
import { ReportsFilters } from './reports-filters';

export const dynamic='force-dynamic';
type Props={searchParams?:Promise<Record<string,string|string[]|undefined>>};

export default async function AdminReportsPage({searchParams}:Props){const params=(await searchParams)??{};const period=String(params.period??'30d');const data=await getAdminReports();const points=data.chart.slice(period==='today'?-1:period==='7d'?-7:period==='year'?0:-30);return <div className="space-y-6"><Header title="التقارير" desc="تقارير مختصرة عن المستخدمين والمشاريع والإيرادات."/><ReportsFilters/><section className="grid gap-4 md:grid-cols-3"><StatCard title="الإيرادات" value={`$${data.stats.revenue.toFixed(2)}`} icon="💵"/><StatCard title="رصيد الضمان" value={`$${data.stats.escrow.toFixed(2)}`} icon="🔒" tone="violet"/><StatCard title="العقود النشطة" value={data.stats.activeContracts} icon="📝" tone="emerald"/></section><section className="rounded-2xl border bg-white p-6 shadow-sm"><h2 className="text-lg font-extrabold text-[#1a1a2e]">رسم الإيرادات</h2><RevenueChart points={points}/></section><section className="grid gap-6 lg:grid-cols-2"><Box title="الأدوار">{data.roles.map(r=><Line key={r.role} label={r.role} value={r.total}/>)}</Box><Box title="حالات المشاريع">{data.projectStatus.map(r=><Line key={r.status} label={r.status} value={r.total}/>)}</Box></section></div>}
function RevenueChart({points}:{points:{day:number;revenue:number}[]}){const max=Math.max(...points.map(p=>p.revenue),1);const width=400;const height=200;const step=points.length>1?width/(points.length-1):width;const d=points.map((p,i)=>`${i===0?'M':'L'} ${i*step} ${height-(p.revenue/max)*(height-20)-10}`).join(' ');return <svg viewBox={`0 0 ${width} ${height}`} className="mt-4 h-64 w-full rounded-xl bg-slate-50"><path d={d} fill="none" stroke="#2386c8" strokeWidth="4" strokeLinecap="round"/><path d={`${d} L ${width} ${height} L 0 ${height} Z`} fill="#2386c8" opacity="0.12"/>{points.map((p,i)=><circle key={p.day} cx={i*step} cy={height-(p.revenue/max)*(height-20)-10} r="4" fill="#1a1a2e"/> )}</svg>}
function Header({title,desc}:{title:string;desc:string}){return <div><h1 className="text-3xl font-extrabold text-[#1a1a2e]">{title}</h1><p className="mt-2 text-sm text-slate-500">{desc}</p></div>}
function Box({title,children}:{title:string;children:React.ReactNode}){return <div className="rounded-2xl border bg-white p-6 shadow-sm"><h2 className="text-lg font-extrabold text-[#1a1a2e]">{title}</h2><div className="mt-4 space-y-2">{children}</div></div>}
function Line({label,value}:{label:string;value:number}){return <div className="flex justify-between rounded-xl bg-slate-50 px-4 py-3"><span>{label}</span><b>{value}</b></div>}
