import { Link } from '@/i18n/navigation';
import { getAdminUsers } from '@/app/actions/admin';
import { DataTable } from '@/components/admin/data-table';
import { StatusBadge } from '@/components/admin/status-badge';
import { ExportButton } from '@/components/admin/export-modal';
import { ResetPasswordButton } from './reset-password-button';
import { SuspendUserButton } from './suspend-user-button';

type Props = { searchParams?: Promise<Record<string, string | string[] | undefined>> };
export const dynamic = 'force-dynamic';

export default async function AdminUsersPage({ searchParams }: Props) {
  const params = (await searchParams) ?? {};
  const rows = await getAdminUsers({ role: String(params.role ?? ''), kyc: String(params.kyc ?? ''), q: String(params.q ?? '') });
  return <div className="space-y-6"><Header title="المستخدمون" desc="إدارة المستخدمين والأدوار وحالة KYC."/><div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><form className="grid gap-3 md:grid-cols-4"><input name="q" placeholder="بحث بالاسم أو البريد" className="rounded-xl border border-slate-200 px-4 py-2 text-sm"/><select name="role" className="rounded-xl border border-slate-200 px-4 py-2 text-sm"><option value="">كل الأدوار</option><option value="client">عميل</option><option value="freelancer">مستقل</option><option value="admin">مشرف</option></select><select name="kyc" className="rounded-xl border border-slate-200 px-4 py-2 text-sm"><option value="">كل حالات KYC</option><option value="verified">موثق</option><option value="unverified">غير موثق</option></select><button className="rounded-xl bg-[#1a1a2e] px-4 py-2 text-sm font-bold text-white">تصفية</button></form><div className="mt-3 flex gap-2"><ExportButton title="المستخدمون" data={rows.map((user) => ({ name: user.name, email: user.email, role: user.role, kyc: user.isKycVerified ? 'موثق' : 'غير موثق', status: user.isActive ? 'نشط' : 'معطل', balance: user.balance ?? '0.00' }))} columns={[{ key: 'name', label: 'الاسم' }, { key: 'email', label: 'البريد' }, { key: 'role', label: 'الدور' }, { key: 'kyc', label: 'KYC' }, { key: 'status', label: 'الحالة' }, { key: 'balance', label: 'الرصيد' }]} /></div></div><DataTable columns={['المستخدم','البريد','الدور','توثيق الهوية','الحالة','الرصيد','التسجيل','آخر تحديث','الإجراءات']} empty={rows.length===0}>{rows.map((user)=><tr key={user.id}><td className="px-4 py-3"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-full bg-[#1a1a2e] font-bold text-white">{user.name.slice(0,1)}</div><b>{user.name}</b></div></td><td className="px-4 py-3" dir="ltr">{user.email}</td><td className="px-4 py-3"><StatusBadge status={user.role}>{user.role}</StatusBadge></td><td className="px-4 py-3"><StatusBadge status={user.isKycVerified?'approved':'pending'}>{user.isKycVerified?'موثق':'غير موثق'}</StatusBadge></td><td className="px-4 py-3"><StatusBadge status={user.isActive?'active':'cancelled'}>{user.isActive?'نشط':'معطل'}</StatusBadge></td><td className="px-4 py-3">{user.balance??'0.00'}</td><td className="px-4 py-3">{user.createdAt.toLocaleDateString('ar')}</td><td className="px-4 py-3">{user.updatedAt.toLocaleDateString('ar')}</td><td className="px-4 py-3"><div className="flex flex-wrap items-center gap-2"><Link href={`/admin/users/${user.id}`} className="rounded-lg bg-[#2386c8]/10 px-3 py-1.5 text-xs font-bold text-[#2386c8] hover:bg-[#2386c8]/20">عرض</Link><SuspendUserButton userId={user.id} isActive={user.isActive}/><ResetPasswordButton userId={user.id} userEmail={user.email} userName={user.name}/></div></td></tr>)}</DataTable></div>;
}
function Header({ title, desc }: { title: string; desc: string }) { return <div><h1 className="text-3xl font-extrabold text-[#1a1a2e]">{title}</h1><p className="mt-2 text-sm text-slate-500">{desc}</p></div>; }
